# -*- coding: utf-8 -*-
"""DLBasics2025_competition_EEG_v8_MAEEGConformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WBR-dZ9RfEW6xyCW0ATOTSiVR48rsr1I

# Deep Learning 基礎講座　最終課題: 脳波分類

## 概要
被験者が画像を見ているときの脳波から，その画像がどのカテゴリに属するかを分類するタスク．
- サンプル数: 訓練 118,800 サンプル，検証 59,400 サンプル，テスト 59,400 サンプル
- クラス数: 5
- 入力: 脳波データ（チャンネル数 x 系列長）
- 出力: 対応する画像のクラス
- 評価指標: Top-1 accuracy

### 元データセット ([Gifford2022 EEG dataset](https://osf.io/3jk45/)) との違い

- 本コンペでは難易度調整の目的で元データセットにいくつかの改変を加えています．

1. 訓練セットのみの使用
  - 元データセットでは訓練データに存在しなかったクラスの画像を見ているときの脳波においてテストが行われますが，これは難易度が非常に高くなります．
  - 本コンペでは元データセットの訓練セットを再分割し，訓練時に存在した画像に対応する別の脳波において検証・テストを行います．

2. クラス数の減少
  - 元データセット（の訓練セット）では16,540枚の画像に対し，1,654のクラスが存在します．
    - e.g. `aardvark`, `alligator`, `almond`, ...
  - 本コンペでは1,654のクラスを，`animal`, `food`, `clothing`, `tool`, `vehicle`の5つにまとめています．
    - e.g. `aardvark -> animal`, `alligator -> animal`, `almond -> food`, ...

### 考えられる工夫の例

- 音声モデルの導入
  - 脳波と同じ波である音声を扱うアーキテクチャを用いることが有効であると知られています．
  - 例）Conformer [[Gulati+ 2020](https://arxiv.org/abs/2005.08100)]
- 画像データを用いた事前学習
  - 本コンペのタスクは脳波のクラス分類ですが，配布してある画像データを脳波エンコーダの事前学習に用いることを許可します．
  - 例）CLIP [Radford+ 2021]
  - 画像を用いる場合は[こちら](https://osf.io/download/3v527/)からダウンロードしてください．
- 過学習を防ぐ正則化やドロップアウト

## 修了要件を満たす条件
- ベースラインモデルのbest test accuracyは38.7%となります．**これを超えた提出のみ，修了要件として認めます**．
- ベースラインから改善を加えることで，55%までは性能向上することを運営で確認しています．こちらを 1 つの指標として取り組んでみてください．

## 注意点
- 最終的な予測モデルは，**配布している訓練データを用いて学習**（ファインチューニング含む）したものとしてください．
- 学習を行わず，**事前学習済みモデルの知識のみを利用した推論は禁止**します．  
（例: ChatGPT 等の LLM に入力して推論を得るのみ）

### 事前学習モデルの利用
許可される事項
- **構成要素としての事前学習モデルの利用**: 自身で実装したアーキテクチャの一部（特徴抽出，埋め込みなど）として事前学習モデル（BERT，ViT など）を利用することは可能です．
- **ファインチューニング**: 上記の用途で利用している事前学習モデルのファインチューニングは可能です．

禁止される事項  
- **タスク解決用の事前学習モデルの利用**: transformers などで提供されている，対象タスクを直接解くための事前学習モデルでそのまま推論のみ，またはファインチューニングのみで利用することは禁止とします．
  - 禁止事項の例: VQA タスクを直接解くための事前学習モデルを VQA タスクで利用する．

## 1.準備
"""

# omnicampus 実行用
!pip install ipywidgets

!pip install optuna

# ライブラリのインポートとシード固定
import os, sys
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter
from einops.layers.torch import Rearrange
from einops import repeat
from glob import glob
from termcolor import cprint
from tqdm.notebook import tqdm
#import optuna

SEED = 0
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ドライブのマウント（Colabの場合）
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# ワーキングディレクトリを作成し移動．ノートブックを配置したディレクトリに適宜書き換え
WORK_DIR = '/content/drive/MyDrive/Colab_Notebooks/DLbasic/FinalAssignment'
#'/content/drive/MyDrive/Colab_Notebooks/DLbasic/FinalAssignment'
#'/workspace/EEG'
#'/content/drive/MyDrive/Colab_Notebooks/DLbasic/FinalAssignment'
#"/content/drive/MyDrive/weblab/DLBasics2025/Competition"
os.makedirs(WORK_DIR, exist_ok=True)
# %cd {WORK_DIR}

"""## 2.データセット

ノートブックと同じディレクトリに`data/`が存在することを確認してください．

データセットロード
"""

# @title
class ThingsEEGDataset(torch.utils.data.Dataset):
    def __init__(self, split: str) -> None:
        super().__init__()

        assert split in ["train", "val", "test"], f"Invalid split: {split}"
        self.split = split
        self.num_classes = 5
        self.num_subjects = 10

        self.X = np.load(f"data/{split}/eeg.npy")
        self.X = torch.from_numpy(self.X).to(torch.float32)
        self.subject_idxs = np.load(f"data/{split}/subject_idxs.npy")
        self.subject_idxs = torch.from_numpy(self.subject_idxs)

        if split in ["train", "val"]:
            self.y = np.load(f"data/{split}/labels.npy")
            self.y = torch.from_numpy(self.y)

        print(f"EEG: {self.X.shape}, labels: {self.y.shape if hasattr(self, 'y') else None}, subject indices: {self.subject_idxs.shape}")

    def __len__(self) -> int:
        return len(self.X)

    '''
    データ拡張
    どのモデルでも精度が上がらない
    改善方針
    ＞適当に全部掛けたらデータが破壊されすぎて学習の妨げになってるかもしれないと仮説を立てたので、確率p_augでどれか一つを選ぶようにｓる
    '''
    def __getitem__(self, i):
        x = self.X[i]

        #mean = x.mean(dim=1, keepdim=True)
        #>>>サンプル単位での正規化に変更
        mean = x.mean()
        #std = x.std(dim=1, keepdim=True)
        std = x.std()
        x = (x-mean) / (std + 1e-6)

        if self.split == 'train':

            p_aug = 0.7
            if torch.rand(1) < p_aug:
                aug_type = torch.randint(0, 5, (1,)).item()
#noise
                if aug_type == 0:
                    noise = torch.randn_like(x) * 0.05
                    x = x+noise
#shift
                elif aug_type == 1:
                    shift = torch.randint(-3, 3, (1,)).item()
                    x = torch.roll(x, shifts=shift, dims=1)
#dropout channel
                elif aug_type == 2:
                    num_drop = torch.randint(1, 4, (1,)).item()
                    drop_idx = torch.randperm(x.shape[0])[:num_drop]
                    x[drop_idx] = 0
#なんか間違えて2回やってる

                elif aug_type == 3:
                    shift = torch.randint(-3, 3, (1,)).item()
                    x = torch.roll(x, shifts=shift, dims=1)

#time mask
                elif aug_type == 4:
                    t_start = torch.randint(0, 85, (1,)).item()
                    t_len = torch.randint(5, 15, (1,)).item()
                    x[:, t_start:t_start+t_len] = 0
#scaling
                elif aug_type == 5:
                    scale = torch.empty(1).uniform_(0.8, 1.2)
                    x = x * scale

        if hasattr(self, "y"):
            return x, self.y[i], self.subject_idxs[i]
        else:
            return x, self.subject_idxs[i]

    @property
    def num_channels(self) -> int:
        return self.X.shape[1]

    @property
    def seq_len(self) -> int:
        return self.X.shape[2]

# @title
#グラフとしての可視化
import matplotlib.pyplot as plt

# データセットのロード
train_set_viz = ThingsEEGDataset("train")

# 可視化するサンプル数とチャンネル数
num_samples_to_plot = 3
num_channels_to_plot = 5 # 各サンプルで表示するチャンネル数

# FigureとAxesの準備
fig, axes = plt.subplots(num_samples_to_plot, 1, figsize=(15, 5 * num_samples_to_plot))

# 複数のサンプルをプロット
for i in range(num_samples_to_plot):
    eeg_data, label, subject_idx = train_set_viz[i]

    # 選択したチャンネルをプロット
    for channel_idx in range(num_channels_to_plot):
        axes[i].plot(eeg_data[channel_idx].cpu().numpy(), label=f'Channel {channel_idx}')

    axes[i].set_title(f'Sample {i+1} (Label: {label.item()}, Subject: {subject_idx.item()})')
    axes[i].set_xlabel('Time Steps')
    axes[i].set_ylabel('Amplitude')
    axes[i].legend()
    axes[i].grid(True)

plt.tight_layout()
plt.show()

# @title
#数値としての可視化
import matplotlib.pyplot as plt

# データセットのロード
train_set_viz = ThingsEEGDataset("train")

# 訓練データセットから最初のサンプルを取得
eeg_data_sample1, label_sample1, subject_idx_sample1 = train_set_viz[0]

print(f"--- Sample 1 Numerical Details ---")
print(f"Label: {label_sample1.item()}")
print(f"Subject Index: {subject_idx_sample1.item()}")
print(f"EEG Data Shape: {eeg_data_sample1.shape}")
print(f"EEG Data (first 5 channels, first 10 time steps):\n{eeg_data_sample1[:5, :10].cpu().numpy()}")

"""↓何かしら使うクラス定義する場所↓"""

# @title
import math

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=500, dropout=0.1):
        super().__init__()
        self.dropout = nn.Dropout(dropout)

        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))  # (1, max_len, d_model)

    def forward(self, x):
        x = x + self.pe[:, :x.size(1), :]
        return self.dropout(x)
#学習可能Posenc
class PositionalEncodingV2(nn.Module):
    def __init__(self, d_model, max_len=100):
        super().__init__()
        self.pos_embed = nn.Parameter(torch.zeros(1, max_len, d_model))#サイズに合わせた学習可能な0を定義する
    def forward(self, x):
        #x: (Batch, Time, Dim)
        #データの長さに合わせて位置情報を足す
        return x + self.pos_embed[:, :x.size(1), :]

class AttentionPooling(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        self.attention_weight = nn.Linear(d_model, 1)#dmodel,1
    def forward(self, x):
        #x:(B, SeqLen, d_model)
        scores  = self.attention_weight(x)
        weights = torch.softmax(scores, dim=1)
        output = (x * weights).sum(dim=1)#(B, SeqLen, 1)
        return output  #(B, d_model)

class GatedAttentionPooling(nn.Module):
    def __init__(self, d_model):
        super().__init__()
        #特徴抽出 (Tanh)
        self.linear_v = nn.Linear(d_model, d_model)
        #ゲート(Sigmoid) でどれくらい通すか決める
        self.linear_u = nn.Linear(d_model, d_model)
        #最終的に1つのスコアにする重
        self.linear_w = nn.Linear(d_model, 1)

    def forward(self, x):
        #x: (Batch, SeqLen, d_model)
        #1. ゲートメカニズム
        #vは特徴変換uはゲート開閉
        v = torch.tanh(self.linear_v(x))
        u = torch.sigmoid(self.linear_u(x))
        gated_features = v * u
        #2. スコア計算
        #ゲートを通った特徴をもとにスコアを出す
        scores = self.linear_w(gated_features) #(B, SeqLen, 1)

        weights = torch.softmax(scores, dim=1)
        output = (x * weights).sum(dim=1)
        return output


#EEGHybridのConvブロック用のSqueezeExcitation Attention
class SELayer(nn.Module):
    def __init__(self, channel, reduction=8):
        super(SELayer, self).__init__()
#２ｄでいいのか？
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(channel, channel // reduction, bias=False),
            nn.ReLU(inplace=True),
            nn.Linear(channel//reduction, channel, bias=False),
            nn.Sigmoid()
        )

    def forward(self, x):
        b, c, _, _ = x.size()
        y = self.avg_pool(x).view(b, c)
        y = self.fc(y).view(b, c, 1, 1)
        return x * y.expand_as(x)

#nn.SiLUがなぜか動かない
class Swish(nn.Module):
    def forward(self, x):
        return x * torch.sigmoid(x)

class ConformerBlock(nn.Module):
    def __init__(self, d_model=64, n_heads=4, conv_kernel_size=15, dropout=0.1):
        super().__init__()
        #Feed Forward Module 1
        self.ff1 = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model * 4),
            Swish(),
            nn.Dropout(dropout),
            nn.Linear(d_model * 4, d_model),
            nn.Dropout(dropout)
        )
        #Multi-Head Self-Attention
        self.attn_norm = nn.LayerNorm(d_model)
        self.attn = nn.MultiheadAttention(d_model, n_heads, dropout=dropout, batch_first=True)
        self.attn_dropout = nn.Dropout(dropout)

        #Convolution Module
        self.conv_norm = nn.LayerNorm(d_model)

        self.conv = nn.Sequential(
            #Pointwise Conv
            nn.LayerNorm(d_model),
            nn.Conv1d(d_model, d_model * 2, kernel_size=1),
            nn.GLU(dim=1),  #d_model * 2 >> d_model
            #Depthwise Conv
            nn.Conv1d(
                d_model,
                d_model,
                kernel_size=conv_kernel_size,
                padding=conv_kernel_size // 2, groups=d_model),
            nn.BatchNorm1d(d_model),
            Swish(),
            #Pointwise Conv
            nn.Conv1d(d_model, d_model, kernel_size=1),
            nn.Dropout(dropout)
        )

        #Feed Forward Module 2
        self.ff2 = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model * 4),
            Swish(),
            nn.Dropout(dropout),
            nn.Linear(d_model * 4, d_model),
            nn.Dropout(dropout)
        )

        self.final_norm = nn.LayerNorm(d_model)

    def forward(self, x):
        #x(Batch, Time, Dim)
        #Feed Forward 1 (half residual)
        x = x + 0.5 * self.ff1(x)

        #Self-Attention
        x_norm = self.attn_norm(x)
        attn_out, _ = self.attn(x_norm, x_norm, x_norm)
        x = x + self.attn_dropout(attn_out)
        #Convolution
        x_norm = self.conv_norm(x)
        x_conv = x_norm.transpose(1, 2)  # (B, D, T) for Conv1d
        x_conv = self.conv(x_conv)
        x_conv = x_conv.transpose(1, 2)  # (B, T, D)
        x = x + x_conv
        #Feed Forward 2 (half residual)
        x = x + 0.5 * self.ff2(x)

        return self.final_norm(x)

class ConformerBlockV2(nn.Module):
    def __init__(self, d_model=64, n_heads=4, conv_kernel_size=31, dropout=0.1):
        super().__init__()

        # Feed Forward Module 1
        self.ffn1 = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model * 4),
            Swish(),
            nn.Dropout(dropout),
            nn.Linear(d_model * 4, d_model),
            nn.Dropout(dropout),
        )

        # Multi-Head Self-Attention
        self.attn_norm = nn.LayerNorm(d_model)
        self.self_attn = nn.MultiheadAttention(
            embed_dim=d_model, num_heads=n_heads,
            dropout=dropout, batch_first=True
        )
        self.attn_dropout = nn.Dropout(dropout)

        # Convolution Module
        self.conv_norm = nn.LayerNorm(d_model)
        self.pw_conv1 = nn.Conv1d(d_model, d_model * 2, kernel_size=1)
        self.glu = nn.GLU(dim=1)
        self.dw_conv = nn.Conv1d(
            d_model, d_model,
            kernel_size=conv_kernel_size,
            padding=(conv_kernel_size - 1) // 2,
            groups=d_model,
        )
        self.dw_norm = nn.LayerNorm(d_model)
        self.dw_act = Swish()
        self.pw_conv2 = nn.Conv1d(d_model, d_model, kernel_size=1)
        self.conv_dropout = nn.Dropout(dropout)

        # Feed Forward Module 2
        self.ffn2 = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, d_model * 4),
            Swish(),
            nn.Dropout(dropout),
            nn.Linear(d_model * 4, d_model),
            nn.Dropout(dropout),
        )

        self.final_norm = nn.LayerNorm(d_model)

    def forward(self, x):
        # x: (B, T, D)
        #Feed Forward 1 (half-step)
        x = x + 0.5 * self.ffn1(x)

        #Self-Attention
        x_norm = self.attn_norm(x)
        attn_out, _ = self.self_attn(x_norm, x_norm, x_norm)  # (B, T, D)
        x = x + self.attn_dropout(attn_out)

        #Convolution Module
        residual = x
        x_norm = self.conv_norm(x)              # (B, T, D)
        x_conv = x_norm.transpose(1, 2)         # (B, D, T)

        x_conv = self.pw_conv1(x_conv)          # (B, 2D, T)
        x_conv = self.glu(x_conv)               # (B, D, T)

        x_conv = self.dw_conv(x_conv)           # (B, D, T)
        x_conv = x_conv.transpose(1, 2)         # (B, T, D)
        x_conv = self.dw_norm(x_conv)
        x_conv = self.dw_act(x_conv)
        x_conv = x_conv.transpose(1, 2)         # (B, D, T)

        x_conv = self.pw_conv2(x_conv)          # (B, D, T)
        x_conv = x_conv.transpose(1, 2)         # (B, T, D)

        x = residual + self.conv_dropout(x_conv)

        #Feed Forward 2 (half-step)
        x = x + 0.5 * self.ffn2(x)

        return self.final_norm(x)

"""## 3.ベースラインモデル

# **EEGNetwithAttn**
"""

# @title
class EEGNetHybrid(nn.Module):#EEGNetにTransformerがっちゃんｋ
    def __init__(
        self,
        num_classes=5,
        in_channels=17,
        time_steps=100,
        num_subjects=11
    ):
        super().__init__()

        #Input channel=17, timelen=100
        self.spatial_conv_1st = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=(in_channels, 1), bias=False),
            nn.BatchNorm2d(32),#32
            nn.GELU(),
            SELayer(channel=32, reduction=4)
            #nn.Dropout(0.25),
            #GELUdeiinoka?
        )

        self.temporal_conv_2nd = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=(1,  5), padding=(0, 2)),
            nn.BatchNorm2d(64),
            nn.GELU(),
            #これ試し
            #SELayer(channel=64, reduction=8),
            nn.AvgPool2d(kernel_size=(1, 2)),
            nn.Dropout(0.25),
        )

        self.d_model = 64
        #transformerへの入力の太さ
        self.positional_encoding = PositionalEncoding(d_model=self.d_model, max_len=time_steps)
        self.subject_embed = nn.Embedding(num_subjects, self.d_model)
        nn.init.normal_(self.subject_embed.weight, std=0.02)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=self.d_model,#64
            nhead=8,
            dim_feedforward=768,
            batch_first=True,
            dropout=0.1
        ) #FF128->256

        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)
        #elf.flatten_dim = 50*64
        self.pool = GatedAttentionPooling(self.d_model)
        self.classifier = nn.Linear(self.d_model, num_classes)
        #self.classifier = nn.Linear(self.d_model, num_classes)->これもうごかんなる

    def forward(self, x, subject_idxs):
        x = x.unsqueeze(1) #conv2dに入れるため
        x = self.spatial_conv_1st(x)
        x = self.temporal_conv_2nd(x)
        #x = self.temporal_conv_1st(x)# -> (Batch, 8, 17, 100)
        #x = self.spatial_conv_2nd(x) # -> (Batch, 64, 1, 25)
        x = x.squeeze(2).permute(0, 2, 1)
        x = self.positional_encoding(x)#追加
        x = self.transformer(x)
        x = self.pool(x)
        #x = x.reshape(x.size(0), -1) #->flattenに対応
        x = self.classifier(x)
        return x

"""# **PlainEEGNet**"""

class EEGNet(nn.Module):
    def __init__(self, num_classes=5, in_channels=17, time_steps=100):
        super().__init__()

        self.spatial_conv_1st = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=(in_channels, 1), bias=False),
            nn.BatchNorm2d(32),#32
            nn.GELU()
        )
        self.temporal_conv_2nd = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=(1,  5), padding=(0, 2)),
            nn.BatchNorm2d(64),
            nn.GELU(),
            nn.AvgPool2d(kernel_size=(1, 2)),
            nn.Dropout(0.25),
        )
        self.flatten_dim = 50*64
        self.classifier = nn.Linear(self.flatten_dim, num_classes)

    def forward(self, x):
        x = x.unsqueeze(1)
        x = self.spatial_conv_1st(x)
        x = self.temporal_conv_2nd(x)
        x = x.reshape(x.size(0), -1)
        x = self.classifier(x)
        return x

"""# **EEGConformer**"""

class EEGConformer(nn.Module):
    def __init__(
            self, num_classes=5,
            in_channels=17,
            time_steps=100,
            d_model=64,
            n_heads=4,
            n_layers=2,
            dropout=0.1,
            num_subjects=11
    ):
        super().__init__()

        self.d_model = d_model
        #Input channel=17, timelen=100
        self.spatial_conv_1st = nn.Sequential(
            nn.Conv2d(1, 32, kernel_size=(in_channels, 1), bias=False),
            nn.BatchNorm2d(32),#32
            nn.GELU(),
            SELayer(channel=32, reduction=4)
        )
        self.temporal_conv_2nd = nn.Sequential(
            nn.Conv2d(32, 64, kernel_size=(1,  5), padding=(0, 2)),
            nn.BatchNorm2d(64),
            nn.GELU(),#GELU試
            nn.AvgPool2d(kernel_size=(1, 2)),
            nn.Dropout(dropout),
        )

        self.pos_encoding = PositionalEncodingV2(d_model, max_len=time_steps)
        self.subject_embed = nn.Embedding(num_subjects, d_model)
        nn.init.normal_(self.subject_embed.weight, std=0.02)
        self.conformer_blocks = nn.ModuleList([
            ConformerBlockV2(
                d_model=d_model,
                n_heads = n_heads,
                conv_kernel_size=15,
                dropout=dropout,
                )
            for _ in range(n_layers)
            ])

        self.pool = GatedAttentionPooling(d_model)
        self.classifier = nn.Linear(d_model, num_classes)

    def forward(self, x,subject_idxs):
        x = x.unsqueeze(1)  # (B, 1, 17, 100)
        x = self.spatial_conv_1st(x)  # (B, 32, 1, 100)
        x = self.temporal_conv_2nd(x)  # (B, 64, 1, 50)
        #Transformer/Conformer用に整形
        x = x.squeeze(2).permute(0, 2, 1)  # (B, 50, 64)
        #位置エンコーディング+subjemb
        x = self.pos_encoding(x)
        subj_emb = self.subject_embed(subject_idxs)  # (B, 64)
        x = x + subj_emb.unsqueeze(1)
        #Conformerブロック
        for block in self.conformer_blocks:
            x = block(x)

        # Poolingと分類
        x = self.pool(x)  # (B, 64)
        x = self.classifier(x)  # (B, num_classes)

        return x

"""https://omomuki-tech.com/archives/6185#i-4

# **MAEEG_Plain**
"""

# @title
class MAEEG_Pretrain(nn.Module):
    def __init__(self, in_channels=17, time_steps=100, embed_dim=64, mask_ratio=0.5):#.75>.5
        super().__init__()
        self.mask_ratio = mask_ratio
        self.time_steps = time_steps

        self.patch_embed = nn.Sequential(
            nn.Conv1d(in_channels, embed_dim, kernel_size=1),
            nn.BatchNorm1d(embed_dim),
            nn.GELU()
        )

        self.pos_encoder = PositionalEncodingV2(embed_dim, max_len=time_steps)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, nhead=4, dim_feedforward=768,
            batch_first=True, dropout=0.1
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=2)

        decoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim, nhead=4, dim_feedforward=384,
            batch_first=True, dropout=0.1
        )
        self.transformer_decoder = nn.TransformerEncoder(decoder_layer, num_layers=1)

        self.output_head = nn.Linear(embed_dim, in_channels)

        self.mask_token = nn.Parameter(torch.zeros(1, 1, embed_dim))

        self._init_weights()

    def _init_weights(self):

        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.LayerNorm):
                nn.init.constant_(m.bias, 0)
                nn.init.constant_(m.weight, 1.0)

    #マスキング処理
    def random_masking(self, x):

        N, L, D = x.shape

        len_keep = int(L * (1 - self.mask_ratio))

        noise = torch.rand(N, L, device=x.device)

        ids_shuffle = torch.argsort(noise, dim=1)

        ids_restore = torch.argsort(ids_shuffle, dim=1)

        ids_keep = ids_shuffle[:, :len_keep]

        x_masked = torch.gather(x, dim=1, index=ids_keep.unsqueeze(-1).repeat(1, 1, D))

        #マスク生成 (Loss計算用で 隠した部分を1にする)
        mask = torch.ones([N, L], device=x.device)
        mask[:, :len_keep] = 0
        mask = torch.gather(mask, dim=1, index=ids_restore)

        return x_masked, mask, ids_restore


    def forward(self, x):

        feat = self.patch_embed(x)

        feat = feat.transpose(1, 2)

        feat = feat + self.pos_encoder(torch.zeros_like(feat))

        latent, mask, ids_restore = self.random_masking(feat)

        latent = self.transformer_encoder(latent)

        mask_tokens = self.mask_token.repeat(feat.shape[0], ids_restore.shape[1] - latent.shape[1], 1)

        x_ = torch.cat([latent, mask_tokens], dim=1)

        x_reconstructed_input = torch.gather(x_, dim=1, index=ids_restore.unsqueeze(-1).repeat(1, 1, feat.shape[2]))

        x_reconstructed_input = x_reconstructed_input + self.pos_encoder.pos_embed

        decoded = self.transformer_decoder(x_reconstructed_input)

        pred = self.output_head(decoded)
        pred = pred.transpose(1, 2)

        return pred, mask

class MAEEG_Classifier(nn.Module):
    def __init__(self, pretrained_model, num_classes=5):
        super().__init__()

        #ptモデルから必要なパーツ(Encoder)だけを引っこ抜く
        #deepcopyして重みを変えずに渡す
        import copy
        self.patch_embed = copy.deepcopy(pretrained_model.patch_embed)
        self.pos_encoder = copy.deepcopy(pretrained_model.pos_encoder)
        self.transformer_encoder = copy.deepcopy(pretrained_model.transformer_encoder)
        self.subject_embed = copy.deepcopy(pretrained_model.subject_embed) # Copy subject embedding as well

        #分類用のヘッド (64次元 -> 5クラス)
        self.classifier = nn.Linear(64, num_classes)
        #self.pool = AttentionPooling(64)
        self.pool = GatedAttentionPooling(64)

    def forward(self, x, subject_idxs):
        # x: (Batch, 17, 100)
        # Encoderの処理 (Pretrainと同じ)
        feat = self.patch_embed(x)       # -> (B, 64, 100)
        feat = feat.transpose(1, 2)      # -> (B, 100, 64)
        feat = feat + self.pos_encoder.pos_embed
        feat = feat + self.subject_embed(subject_idxs).unsqueeze(1) # Fix: Unsqueeze subject embedding

        #マス金ぐしないの大事
        features = self.transformer_encoder(feat) # -> (B, 100, 64)

        #Avgpoolからgatedattnに
        feat_pooled = self.pool(features)

        #分類
        out = self.classifier(feat_pooled)  # -> (B, 5)

        return out

"""↑Catastrophic forgettingをうたがう   
＞＞Pretrainの重みを初期化されてるClassifierが破壊する

# **MAEEG事前学習**
"""

#@title
device = "cuda"
pretrain_model = MAEEG_Pretrain(in_channels=17, time_steps=100).to(device)

#復元誤差 (MSE) で学習
optimizer = torch.optim.AdamW(pretrain_model.parameters(), lr=1e-3, weight_decay=0.05)
criterion = nn.MSELoss()

batch_size = 128
train_set = ThingsEEGDataset("train")
train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)

print("--- Start Pre-training ---")
for epoch in range(75): #20~50エポックくらい回す
    pretrain_model.train()
    total_loss = 0

    for X, _, _ in train_loader: #ラベルyは無視
        X = X.to(device)

        #推論 (復元された波形と、どこを隠したかのマスクが返る)
        pred, mask = pretrain_model(X)

        #Loss計算
        #maskは隠した場所が1になっている
        # pred - X) ** 2 で全要素の誤差を出し、maskを掛けて隠した部分だけ残す
        loss = ((pred - X) ** 2 * mask.unsqueeze(1)).sum() / mask.sum()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

    print(f"Epoch {epoch+1} | Loss: {total_loss / len(train_loader):.4f}")

#重みを保存
torch.save(pretrain_model.state_dict(), "mae_pretrained.pt")
print("Pre-training Finished!")

torch.save(pretrain_model.state_dict(), "mae_pretrained1.pt")

def mixup_data(x, y, alpha=0.8):
    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1
    batch_size = x.size(0)
    index = torch.randperm(batch_size).to('cuda')

    mixed_x = lam * x + (1 - lam) * x[index]
    y_a, y_b = y, y[index]

    return mixed_x, y_a, y_b, lam

"""# **MAEEG_WithSubembedding**"""

# @title
class MAEEG_Pretrain_Embedding(nn.Module):
    def __init__(
            self,
            in_channels=17,
            time_steps=100,
            embed_dim=64,
            mask_ratio=0.5,
            num_subjects=11):#.75>.5
        super().__init__()
        self.mask_ratio = mask_ratio
        self.time_steps = time_steps
        self.num_subjects = num_subjects

        self.patch_embed = nn.Sequential(
            nn.Conv1d(in_channels, embed_dim, kernel_size=1),
            nn.BatchNorm1d(embed_dim),
            nn.GELU()
        )

        self.pos_encoder = PositionalEncodingV2(embed_dim, max_len=time_steps)

        self.subject_embed = nn.Embedding(num_subjects, embed_dim)
        nn.init.xavier_uniform_(self.subject_embed.weight)#normal>>xavier

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=4,
            dim_feedforward=512,
            batch_first=True,
            dropout=0.1
        )
        self.transformer_encoder = nn.TransformerEncoder(encoder_layer, num_layers=2)

        decoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=4,
            dim_feedforward=384,
            batch_first=True,
            dropout=0.1
        )

        self.transformer_decoder = nn.TransformerEncoder(decoder_layer, num_layers=1)
        self.output_head = nn.Linear(embed_dim, in_channels)
        self.mask_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self._init_weights()

    def _init_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)

                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)

            elif isinstance(m, nn.LayerNorm):
                nn.init.constant_(m.bias, 0)
                nn.init.constant_(m.weight, 1.0)

    #マスキング処理
    def random_masking(self, x):
        #x=(B,L,D)
        N, L, D = x.shape
        len_keep = int(L * (1 - self.mask_ratio))

        noise = torch.rand(N, L, device=x.device)
        ids_shuffle = torch.argsort(noise, dim=1)
        ids_restore = torch.argsort(ids_shuffle, dim=1)
        ids_keep = ids_shuffle[:, :len_keep]

        x_masked = torch.gather(
            x, dim=1,
            index=ids_keep.unsqueeze(-1).repeat(1, 1, D)
            )

        # 隠した部分を1にする
        mask = torch.ones([N, L], device=x.device)
        mask[:, :len_keep] = 0
        mask = torch.gather(mask, dim=1, index=ids_restore)

        return x_masked, mask, ids_restore


    def forward(self, x, subject_idxs):
        feat = self.patch_embed(x)
        feat = feat.transpose(1, 2)

        feat = feat + self.pos_encoder(torch.zeros_like(feat))
        subj_emb = self.subject_embed(subject_idxs)
        feat = feat + subj_emb.unsqueeze(1)

        latent, mask, ids_restore = self.random_masking(feat)
        latent = self.transformer_encoder(latent)

        mask_tokens = self.mask_token.repeat(feat.shape[0], ids_restore.shape[1] - latent.shape[1], 1)

        x_ = torch.cat([latent, mask_tokens], dim=1)

        x_reconstructed_input = torch.gather(
            x_,
            dim=1,
            index=ids_restore.unsqueeze(-1).repeat(1, 1, feat.shape[2])
            )

        x_reconstructed_input = x_reconstructed_input + self.pos_encoder.pos_embed

        decoded = self.transformer_decoder(x_reconstructed_input)
        pred = self.output_head(decoded)
        pred = pred.transpose(1, 2)

        return pred, mask

class MAEEG_Classifier_Embedding(nn.Module):
    def __init__(self, pretrained_model, num_classes=5, num_subjects=11):
        super().__init__()
        #事前学習済みモデルからEncodeだけをdeepcopy
        import copy
        self.patch_embed = copy.deepcopy(pretrained_model.patch_embed)
        self.pos_encoder = copy.deepcopy(pretrained_model.pos_encoder)
        self.transformer_encoder = copy.deepcopy(pretrained_model.transformer_encoder)
        self.subject_embed = copy.deepcopy(pretrained_model.subject_embed)

        #分類用 (64次元 >> 5クラス)
        self.pool = GatedAttentionPooling(64)
        self.classifier = nn.Linear(64, num_classes)

    def forward(self, x, subject_idxs):
        # x=(Batch, 17, 100)
        #Encoderの処理 (Pretrainと同じ)
        feat = self.patch_embed(x)       # -> (B, 64, 100)
        feat = feat.transpose(1, 2)      # -> (B, 100, 64)
        feat = feat + self.pos_encoder.pos_embed
        feat = feat + self.subject_embed(subject_idxs).unsqueeze(1)
        features = self.transformer_encoder(feat) #-> (B, 100, 64)
        #GatedAttnPooling
        feat_pooled = self.pool(features)
        out = self.classifier(feat_pooled)  # -> (B, 5)
        return out

"""## 事前学習"""

# @title
device = "cuda"
pretrain_model = MAEEG_Pretrain_Embedding(
    in_channels=17,
    time_steps=100,
    embed_dim=64,
    mask_ratio=0.5,
    num_subjects=11
    ).to(device)

#復元誤差 (で学習
optimizer = torch.optim.AdamW(pretrain_model.parameters(), lr=1e-3, weight_decay=0.05)
criterion = nn.MSELoss()

batch_size = 256
train_set = ThingsEEGDataset("train")
train_loader = torch.utils.data.DataLoader(
    train_set,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True)

print("--- Start Pre-training ---")
for epoch in range(75):
    pretrain_model.train()
    total_loss = 0

    for X, _, subject_idxs in train_loader:
        X, subject_idxs = X.to(device), subject_idxs.to(device)

        pred, mask = pretrain_model(X, subject_idxs)

        #Loss計算 (隠された部分だけの誤差を見る
        #maskは隠した場所が1
        #(pred - X) ** 2 で全要素の誤差を出し、maskを掛けて隠した部分だけ残す
        diff2 = (pred - X)**2
        mask_exp = mask.unsqueeze(1)
        loss = (diff2 * mask_exp).sum() / mask_exp.sum()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} | Loss: {total_loss / len(train_loader):.4f}")

#重みを保存しておく
torch.save(pretrain_model.state_dict(), "mae_pretrained.pt")
print("事前学習おしまい")

"""## **MAEEGファインチューニング**"""

# @title
import copy

device = "cuda"
pretrain_model = MAEEG_Pretrain_Embedding(
    in_channels=17,
    time_steps=100,
    embed_dim=64,
    mask_ratio=0.5,
    num_subjects=11
    ).to(device)

try:
    pretrain_model.load_state_dict(torch.load("mae_pretrained.pt"))
    print("事前学習済みの重みのロード完了")
except FileNotFoundError:
    print(" 'mae_pretrained.pt' が見つかりません。ランダム初期化で開始")

model = MAEEG_Classifier_Embedding(
    pretrain_model,
    num_classes=5,
    num_subjects=11
    ).to(device)

batch_size = 128

#データローダー
train_set = ThingsEEGDataset("train")
train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
val_set = ThingsEEGDataset("val")
val_loader = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

criterion = nn.CrossEntropyLoss()

def mixup_data(x, y, alpha=0.8):

    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1.0

    batch_size = x.size(0)
    index = torch.randperm(batch_size).to(device)
    mixed_x = lam * x+(1-lam) * x[index]
    y_a, y_b = y, y[index]
    return mixed_x, y_a, y_b, lam

#catastrophic frgettingの対策
print(" Phase 1: Linear Probing (Head only) ")

for p in model.parameters():
    p.requires_grad = False
for p in model.classifier.parameters():
    p.requires_grad = True
for p in model.pool.parameters():
    p.requires_grad = True

optimizer_warmup = torch.optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-3)

warmup_epochs = 5
for epoch in range(warmup_epochs):
    model.train()
    total_loss = 0.0
    for X, y, subject_idxs in train_loader:
        X = X.to(device)
        y = y.to(device)
        subject_idxs = subject_idxs.to(device)

        optimizer_warmup.zero_grad()
        logits = model(X, subject_idxs)
        loss = criterion(logits, y)
        loss.backward()
        optimizer_warmup.step()
        total_loss += loss.item()
    print(f"Warmup Epoch {epoch+1}/{warmup_epochs} | Loss: {total_loss / len(train_loader):.4f}")

#Phase 2 full fine tuning
for p in model.parameters():
    p.requires_grad = True#Trueで解答

epochs =  65 #100->65
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=0.05)
#scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='max',
    factor=0.5,
    patience=5,
)

#Loss関数 (Mixup用と検証用)
criterion_val = nn.CrossEntropyLoss()

def MixupCrossEntropy(y_a, y_b, lam, preds):
    loss = lam * criterion_val(preds, y_a) + (1 - lam) * criterion_val(preds, y_b)
    return loss

max_val_acc = 0.0
#writer = SummaryWriter("tensorboard")

print("Start Fine-tuning/Classification")
for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}")

    train_loss, train_acc, val_loss, val_acc = [], [], [], []

    model.train()
    for X, y, subject_idxs in tqdm(train_loader, desc="Train"):
        X, y, subject_idxs = X.to(device), y.to(device), subject_idxs.to(device)

        mixed_x, y_a, y_b, lam = mixup_data(X, y, alpha=0.8)
        preds = model(mixed_x, subject_idxs)
        loss = MixupCrossEntropy(y_a, y_b, lam, preds)

        train_loss.append(loss.item())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        acc = (preds.argmax(dim=-1) == y).float().mean()
        train_acc.append(acc.item())

    model.eval()
    for X, y, subject_idxs_val in tqdm(val_loader, desc="Validation"):
        X, y, subject_idxs_val = X.to(device), y.to(device), subject_idxs_val.to(device)

        with torch.no_grad():
            y_pred = model(X, subject_idxs_val) #Corrected variable name

        loss = criterion_val(y_pred, y)
        val_loss.append(loss.item())
        acc = (y_pred.argmax(dim=-1) == y).float().mean()
        val_acc.append(acc.item())

    avg_train_loss = np.mean(train_loss)
    avg_train_acc = np.mean(train_acc)
    avg_val_loss = np.mean(val_loss)
    avg_val_acc = np.mean(val_acc)

    print(f"Epoch {epoch+1}/{epochs} | "
          f"Train Loss: {avg_train_loss:.4f} | Train Acc: {avg_train_acc:.4f} | "
          f"Val Loss: {avg_val_loss:.4f} | Val Acc: {avg_val_acc:.4f}")

    #Tensorboard
    #writer.add_scalar("train_loss", avg_train_loss, epoch)
    #writer.add_scalar("val_acc", avg_val_acc, epoch)
    #スケジューラ更新
    scheduler.step(avg_val_acc)

    #ラストモデル保存
    torch.save(model.state_dict(), "maeegSubemb_classifier_last.pt")

    #べストモデル更新
    if avg_val_acc > max_val_acc:
        print(f"New best! ({max_val_acc:.4f} -> {avg_val_acc:.4f}) Saving model...")
        torch.save(model.state_dict(), "maeegSubemb_classifier_best.pt")
        max_val_acc = avg_val_acc

print("Fine-tuning Finished!")

"""# **MAEConformer**   
エンコーダーをTransformerからConformerガン積みにする
"""

# @title
class ConformerMAEEG_Pretrain(nn.Module):
    def __init__(
        self,
        in_channels=17,
        time_steps=100,
        embed_dim=128,
        mask_ratio=0.6,
        depth=4,
        num_subjects=11,
    ):
        super().__init__()
        self.mask_ratio = mask_ratio
        self.num_subjects = num_subjects
        self.time_steps = time_steps
        self.embed_dim = embed_dim

        #パッチ埋め込み: Conv1d スタック
        self.patch_embed = nn.Sequential(
            nn.Conv1d(in_channels, embed_dim // 2, kernel_size=3, padding=1),
            nn.BatchNorm1d(embed_dim // 2),
            nn.GELU(),
            nn.Conv1d(embed_dim // 2, embed_dim, kernel_size=3, padding=1),
            nn.BatchNorm1d(embed_dim),
            nn.GELU(),
        )

        #埋め込み
        self.pos_encoder = PositionalEncodingV2(embed_dim, max_len=time_steps)

        self.subject_embed = nn.Embedding(num_subjects, embed_dim)
        nn.init.xavier_uniform_(self.subject_embed.weight)

        # EncoderConformerV2ブロック
        self.encoder_blocks = nn.ModuleList([
            ConformerBlockV2(d_model=embed_dim, n_heads=4, conv_kernel_size=15, dropout=0.1)
            for _ in range(depth)
        ])
        #DecodeConformerは使わんしTransformerだけでもロスがめちゃくちゃ下げれるからいらないと判断
        # Decoder軽量TransformerEncoder
        decoder_layer = nn.TransformerEncoderLayer(
            d_model=embed_dim,
            nhead=4,
            dim_feedforward=256,
            batch_first=True,
        )
        self.decoder = nn.TransformerEncoder(decoder_layer, num_layers=1)

        self.mask_token = nn.Parameter(torch.zeros(1, 1, embed_dim))
        self.output_head = nn.Linear(embed_dim, in_channels)

    def random_masking(self, x):
        # x: (B, T, D)
        B, T, D = x.shape
        len_keep = int(T * (1.0 - self.mask_ratio))

        noise = torch.rand(B, T, device=x.device)
        ids_shuffle = torch.argsort(noise, dim=1)
        ids_restore = torch.argsort(ids_shuffle, dim=1)
        ids_keep = ids_shuffle[:, :len_keep]

        x_masked = torch.gather(
            x, dim=1,
            index=ids_keep.unsqueeze(-1).repeat(1, 1, D)
        )

        mask = torch.ones(B, T, device=x.device)
        mask[:, :len_keep] = 0
        mask = torch.gather(mask, dim=1, index=ids_restore)

        return x_masked, mask, ids_restore

    def forward(self, x, subject_idxs):
        """
        x: (B, 17, T=100)
        subject_idxs: (B,)
        """
        #Embed
        feat = self.patch_embed(x)          # (B, D, T)
        feat = feat.transpose(1, 2)         # (B, T, D)

        #埋め込み
        feat = feat + self.pos_encoder.pos_embed[:, :feat.size(1), :]

        subj_emb = self.subject_embed(subject_idxs)     # (B, D)
        feat = feat + subj_emb.unsqueeze(1)            # (B, T, D)

        #Masking
        latent, mask, ids_restore = self.random_masking(feat)

        #Encoder (Conformer)
        for block in self.encoder_blocks:
            latent = block(latent)                     # (B, T_vis, D)

        #Decoder,マスクトークンで長さを戻す
        B, T_vis, D = latent.shape
        T_full = feat.size(1)
        num_mask = T_full - T_vis

        mask_tokens = self.mask_token.expand(B, num_mask, D)  # (B, num_mask, D)
        x_ = torch.cat([latent, mask_tokens], dim=1)          # (B, T_full, D)

        #元の順番に並べ替え
        x_rec = torch.gather(
            x_, dim=1,
            index=ids_restore.unsqueeze(-1).repeat(1, 1, D)
        )

        #Decoder でも位置埋め込みを足す
        x_rec = x_rec + self.pos_encoder.pos_embed[:, :T_full, :]

        #Decoder再構成
        decoded = self.decoder(x_rec)                # (B, T, D)
        pred = self.output_head(decoded)             # (B, T, C)
        pred = pred.transpose(1, 2)                  # (B, C=17, T)

        return pred, mask

#Classifeire
class ConformerMAEEG_Classifier(nn.Module):
    def __init__(self, pretrained_model, num_classes=5, num_subjects=11):
        super().__init__()

        #事前学習モデルから Encoder 関連をコピー
        self.patch_embed     = copy.deepcopy(pretrained_model.patch_embed)
        self.pos_encoder     = copy.deepcopy(pretrained_model.pos_encoder)
        self.encoder_blocks  = copy.deepcopy(pretrained_model.encoder_blocks)
        self.subject_embed   = copy.deepcopy(pretrained_model.subject_embed)

        embed_dim = pretrained_model.output_head.in_features

        self.pool = GatedAttentionPooling(embed_dim)
        self.classifier = nn.Linear(embed_dim, num_classes)

    def forward(self, x, subject_idxs):
        """
        x: (B, 17, T)
        subject_idxs: (B,)
        """
        feat = self.patch_embed(x)          # (B, D, T)
        feat = feat.transpose(1, 2)         # (B, T, D)

        feat = feat + self.pos_encoder.pos_embed[:, :feat.size(1), :]

        subj_emb = self.subject_embed(subject_idxs)   # (B, D)
        feat = feat + subj_emb.unsqueeze(1)           # (B, T, D)

        for block in self.encoder_blocks:
            feat = block(feat)                        # (B, T, D)

        feat_pooled = self.pool(feat)                 # (B, D)
        out = self.classifier(feat_pooled)            # (B, num_classes)
        return out

"""## **事前学習**"""

# @title
device = "cuda"
#pretrain_model = MAEEG_Pretrain_Embedding(
    #in_channels=17,
    #time_steps=100,
    #embed_dim=64,
    #mask_ratio=0.5,
    #num_subjects=11
    #).to(device)

pretrain_model = ConformerMAEEG_Pretrain(
    in_channels=17,
    time_steps=100,
    embed_dim=128,
    depth=4,
    mask_ratio=0.6,
    num_subjects=11
    ).to(device)

# 復元誤差 (MSE) で学習
optimizer = torch.optim.AdamW(pretrain_model.parameters(), lr=1e-3, weight_decay=0.05)
criterion = nn.MSELoss()

batch_size = 128
train_set = ThingsEEGDataset("train")
train_loader = torch.utils.data.DataLoader(
    train_set,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True)

print("--- Start Pre-training ---")
for epoch in range(75):
    pretrain_model.train()
    total_loss = 0

    for X, _, subject_idxs in train_loader:
        X, subject_idxs = X.to(device), subject_idxs.to(device)

        pred, mask = pretrain_model(X, subject_idxs)

        #Loss計算
        #maskは隠した場所が1
        #(pred - X) ** 2 で全要素の誤差を出し、maskを掛けて隠した部分だけ残す
        diff2 = (pred - X)**2
        mask_exp = mask.unsqueeze(1)
        loss = (diff2 * mask_exp).sum() / mask_exp.sum()

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} | Loss: {total_loss / len(train_loader):.4f}")

# 重みを保存しておく
torch.save(pretrain_model.state_dict(), "mae_pretrained.pt")
print("事前学習おしまい")

"""## **ファインチューニング**"""

import copy

device = "cuda"
pretrain_model = ConformerMAEEG_Pretrain(
    in_channels=17,
    time_steps=100,
    embed_dim=128,
    mask_ratio=0.5,
    num_subjects=11
    ).to(device)

try:
    pretrain_model.load_state_dict(torch.load("mae_pretrained.pt"))
    print('事前学習済みの重みのロード完了')
except FileNotFoundError:
    print("'mae_pretrained.pt' が見つかりません。ランダム初期化で開始")

model = ConformerMAEEG_Classifier(
    pretrain_model,
    num_classes=5,
    num_subjects=11
    ).to(device)

batch_size = 64

#データローダー
train_set = ThingsEEGDataset("train")
train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True)
val_set = ThingsEEGDataset("val")
val_loader = torch.utils.data.DataLoader(val_set, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True)

criterion = nn.CrossEntropyLoss()

def mixup_data(x, y, alpha=0.8):

    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1.0

    batch_size = x.size(0)
    index = torch.randperm(batch_size).to(device)
    mixed_x = lam * x+(1-lam) * x[index]
    y_a, y_b = y, y[index]
    return mixed_x, y_a, y_b, lam

#catastrophic frgettingの対策
print("---Linear Probing (Head only) ---")

for p in model.parameters():
    p.requires_grad = False
for p in model.classifier.parameters():
    p.requires_grad = True
for p in model.pool.parameters():
    p.requires_grad = True

optimizer_warmup = torch.optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=1e-3)

warmup_epochs = 5
for epoch in range(warmup_epochs):
    model.train()
    total_loss = 0.0
    for X, y, subject_idxs in train_loader:
        X = X.to(device)
        y = y.to(device)
        subject_idxs = subject_idxs.to(device)

        optimizer_warmup.zero_grad()
        logits = model(X, subject_idxs)
        loss = criterion(logits, y)
        loss.backward()
        optimizer_warmup.step()
        total_loss += loss.item()
    print(f"Warmup Epoch {epoch+1}/{warmup_epochs} | Loss: {total_loss / len(train_loader):.4f}")

#Phase 2 full fine tuning
for p in model.parameters():
    p.requires_grad = True

epochs = 35 #100
optimizer = torch.optim.AdamW(model.parameters(), lr=2e-4, weight_decay=0.05)
#scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode='max',
    factor=0.5,
    patience=5,
)

#Loss関数 (Mixup用と検証用)
criterion_val = nn.CrossEntropyLoss()

def MixupCrossEntropy(y_a, y_b, lam, preds):
    loss = lam * criterion_val(preds, y_a) + (1 - lam) * criterion_val(preds, y_b)
    return loss

max_val_acc = 0.0
#writer = SummaryWriter("tensorboard")

print("Start Fine-tuning/Classification")
for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}")

    train_loss, train_acc, val_loss, val_acc = [], [], [], []

    model.train()
    for X, y, subject_idxs in tqdm(train_loader, desc="Train"):
        X, y, subject_idxs = X.to(device), y.to(device), subject_idxs.to(device)

        mixed_x, y_a, y_b, lam = mixup_data(X, y, alpha=0.8)
        preds = model(mixed_x, subject_idxs)
        loss = MixupCrossEntropy(y_a, y_b, lam, preds)

        train_loss.append(loss.item())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        acc = (preds.argmax(dim=-1) == y).float().mean()
        train_acc.append(acc.item())

    model.eval()
    for X, y, subject_idxs_val in tqdm(val_loader, desc="Validation"):
        X, y, subject_idxs_val = X.to(device), y.to(device), subject_idxs_val.to(device)

        with torch.no_grad():
            y_pred = model(X, subject_idxs_val) # Corrected variable name

        loss = criterion_val(y_pred, y)
        val_loss.append(loss.item())
        acc = (y_pred.argmax(dim=-1) == y).float().mean()
        val_acc.append(acc.item())

    avg_train_loss = np.mean(train_loss)
    avg_train_acc = np.mean(train_acc)
    avg_val_loss = np.mean(val_loss)
    avg_val_acc = np.mean(val_acc)

    print(f"Epoch {epoch+1}/{epochs} | "
          f"Train Loss: {avg_train_loss:.4f} | Train Acc: {avg_train_acc:.4f} | "
          f"Val Loss: {avg_val_loss:.4f} | Val Acc: {avg_val_acc:.4f}")

    #Tensorboard
    #writer.add_scalar("train_loss", avg_train_loss, epoch)
    #writer.add_scalar("val_acc", avg_val_acc, epoch)
    #スケジューラ更新
    scheduler.step(avg_val_acc)

    # ラストモデル保存
    torch.save(model.state_dict(), "mae_classifier_last.pt")

    # ベストモデル更新
    if avg_val_acc > max_val_acc:
        print(f"New best! ({max_val_acc:.4f} -> {avg_val_acc:.4f}) Saving model...")
        torch.save(model.state_dict(), "mae_classifier_best.pt")
        max_val_acc = avg_val_acc

print("Fine-tuning Finished!")

"""## 4.訓練実行"""

# @title
import torch.optim as optim

def mixup_data(x, y, alpha=1.0):
    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1

    batch_size = x.size(0)
    index = torch.randperm(batch_size).to('cuda')

    mixed_x = lam * x + (1 - lam) * x[index]
    y_a, y_b = y, y[index]

    return mixed_x, y_a, y_b, lam
# ==========================================
# 1. 目的関数の定義 (この中で学習を回す)
# ==========================================
def objective(trial):
    # --- A. Optunaに探索させたいハイパラを登録 ---

    # 1. 学習率 (1e-5 から 1e-2 の間で対数的に探す)
    lr = trial.suggest_float("lr", 1e-5, 1e-2, log=True)

    # 2. バッチサイズ (いくつか候補を挙げる)
    batch_size = trial.suggest_categorical("batch_size", [64, 128, 256])

    # 3. OptimizerのWeight Decay (過学習の抑え具合)
    weight_decay = trial.suggest_float("weight_decay", 1e-5, 1e-1, log=True)

    # 4. Mixupの強さ (alpha)
    mixup_alpha = trial.suggest_float("mixup_alpha", 0.1, 1.0)

    # ----------------------------------------
    # データローダーの準備 (バッチサイズが変わるためここで作る)
    # ----------------------------------------
    train_set = ThingsEEGDataset("train")
    train_loader = torch.utils.data.DataLoader(
        train_set, batch_size=batch_size, shuffle=True, num_workers=2
    )
    val_set = ThingsEEGDataset("val")
    val_loader = torch.utils.data.DataLoader(
        val_set, batch_size=batch_size, shuffle=False, num_workers=2
    )

    # ----------------------------------------
    # モデルとOptimizerの準備
    # ----------------------------------------
    model = EEGNetHybrid().to("cuda")

    # 提案された lr と weight_decay を使う
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=weight_decay)

    # Schedulerもハイパラに合わせて調整してもいいが、一旦固定
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=15) # 探索時は短めでOK
    criterion = nn.CrossEntropyLoss()

    # ----------------------------------------
    # 学習ループ (高速化のためエポック数は減らす)
    # ----------------------------------------
    n_epochs_pruning = 15 # ハイパラ探索用なので、本番(60)より短くする

    for epoch in range(n_epochs_pruning):
        model.train()
        for X, y, _ in train_loader:
            X, y = X.to("cuda"), y.to("cuda")

            # 提案された mixup_alpha を使う
            mixed_x, y_a, y_b, lam = mixup_data(X, y, alpha=mixup_alpha)

            preds = model(mixed_x)
            loss = lam * criterion(preds, y_a) + (1 - lam) * criterion(preds, y_b)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

        scheduler.step()

        # --- 検証 (Pruningの判定) ---
        model.eval()
        val_acc_list = []
        with torch.no_grad():
            for X, y, _ in val_loader:
                X, y = X.to("cuda"), y.to("cuda")
                preds = model(X)
                acc = (preds.argmax(dim=-1) == y).float().mean().item()
                val_acc_list.append(acc)

        avg_val_acc = np.mean(val_acc_list)

        # --- B. Pruning (見込みのない試行の切り捨て) ---
        # Optunaに現在の精度を報告
        trial.report(avg_val_acc, epoch)

        # 「この学習率じゃ全然ダメだわ」と判断されたら、強制終了して次の試行へ
        if trial.should_prune():
            raise optuna.TrialPruned()

    # 最終的な検証精度を返す (これを最大化するのが目的)
    return avg_val_acc

# ==========================================
# 2. 最適化の実行
# ==========================================
# study（実験管理オブジェクト）を作成
# direction="maximize" -> 正解率(accuracy)なので「最大化」を目指す
study = optuna.create_study(direction="maximize")

print("Start optimization...")
# n_trials=20 : 20通り試す (時間があれば50くらいやりたい)
study.optimize(objective, n_trials=20)

# ==========================================
# 3. 結果の確認と本番学習
# ==========================================
print("Best trial:")
trial = study.best_trial

print(f"  Value: {trial.value}")
print("  Params: ")
for key, value in trial.params.items():
    print(f"    {key}: {value}")

# ★ここで出た「Best Params」を使って、
# エポック数を60に戻して本番学習(train)を実行してください！

# @title
#hiddim>768, attnpool
import numpy as np
# ハイパラ
lr = 0.0004
batch_size = 64
epochs = 75

train_set = ThingsEEGDataset("train")
train_loader = torch.utils.data.DataLoader(
    train_set,
    batch_size=batch_size,
    shuffle=True,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True
)
val_set = ThingsEEGDataset("val")
val_loader = torch.utils.data.DataLoader(
    val_set,
    batch_size=batch_size,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
    persistent_workers=True
)

#model = BasicConvClassifier(
   # train_set.num_classes, train_set.seq_len, train_set.num_channels
#).to("cuda")
model = EEGNetHybrid().to('cuda')
'''
model = EEGConformer(
    num_classes=5,
    in_channels=17,
    time_steps=100,
    d_model=64,
    n_heads=4,
    n_layers=2,  # Conformerブロック数
    dropout=0.1,
    num_subjects=11
    ).to('cuda')
    '''
#model = MAEEG_Classifier(pretrain_model, num_classes=5).to(device)

optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.003)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

max_val_acc = 0
def accuracy(y_pred, y):
    return (y_pred.argmax(dim=-1) == y).float().mean()

def mixup_data(x, y, alpha=0.8):
    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1
    batch_size = x.size(0)
    index = torch.randperm(batch_size).to('cuda')

    mixed_x = lam * x + (1 - lam) * x[index]
    y_a, y_b = y, y[index]

    return mixed_x, y_a, y_b, lam

writer = SummaryWriter("tensorboard")

"""### ↓EEGHybrid等用"""

# @title
for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}")

    train_loss, train_acc, val_loss, val_acc = [], [], [], []

    model.train()
    for X, y, subject_idxs in tqdm(train_loader, desc="Train"):
        X, y, subject_idxs = X.to("cuda"), y.to("cuda"), subject_idxs.to('cuda')

        mixed_x, y_a, y_b, lam = mixup_data(X, y, alpha=0.8)

        preds = model(mixed_x, subject_idxs)
        #y_pred = model(X)

        #loss = F.cross_entropy(y_pred, y)
        loss = lam * criterion(preds, y_a) + (1 - lam) * criterion(preds, y_b)

        train_loss.append(loss.item())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        #acc= accuracy y_pred, y)
        acc = (preds.argmax(dim=-1) == y).float().mean()
        train_acc.append(acc.item())

    scheduler.step()

    model.eval()
    for X, y, subject_idxs in tqdm(val_loader, desc="Validation"):
        X, y, subject_idxs = X.to("cuda"), y.to("cuda"), subject_idxs.to('cuda')

        with torch.no_grad():
            y_pred = model(X, subject_idxs)

        val_loss.append(criterion(y_pred, y).item())
        #val_acc.append(accuracy(y_pred, y).item())
        val_acc.append((y_pred.argmax(dim=-1) == y).float().mean().item())

    print(f"Epoch {epoch+1}/{epochs} | \
        train loss: {np.mean(train_loss):.3f} | \
        train acc: {np.mean(train_acc):.3f} | \
        val loss: {np.mean(val_loss):.3f} | \
        val acc: {np.mean(val_acc):.3f}")

    writer.add_scalar("train_loss", np.mean(train_loss), epoch)
    writer.add_scalar("train_acc", np.mean(train_acc), epoch)
    writer.add_scalar("val_loss", np.mean(val_loss), epoch)
    writer.add_scalar("val_acc", np.mean(val_acc), epoch)

    torch.save(model.state_dict(), "model_last_conf.pt")

    if np.mean(val_acc) > max_val_acc:
        cprint("New best. Saving the model.", "cyan")
        torch.save(model.state_dict(), "model_best_eeghyb.pt")
        max_val_acc = np.mean(val_acc)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir tensorboard

"""## 5.評価"""



# Dataloader
batch_size = 128
test_set = ThingsEEGDataset("test")
test_loader = torch.utils.data.DataLoader(
    test_set, batch_size=batch_size, shuffle=False
)

#model = EEGNetHybrid().to("cuda")
'''
model = EEGConformer(
    num_classes=5,
    in_channels=17,
    time_steps=100,
    d_model=64,
    n_heads=4,
    n_layers=2,  # Conformerブロック数
    dropout=0.1
    ).to('cuda')
    '''
#model = MAEEG_Classifier_Embedding(pretrain_model, num_classes=5, num_subjects=11).to("cuda")
pretrain_model = ConformerMAEEG_Pretrain(
    in_channels=17,
    time_steps=100,
    embed_dim=128,
    depth=4,
    mask_ratio=0.6,
    num_subjects=11
    ).to(device)

model = ConformerMAEEG_Classifier(pretrain_model, num_classes=5, num_subjects=11).to("cuda")
#model.load_state_dict(torch.load("model_best_eeg.pt", map_location="cuda"))
model.load_state_dict(torch.load("mae_classifier_best.pt", map_location="cuda"))
#evalui
preds = []
model.eval()
for X, subject_idxs in tqdm(test_loader, desc="Evaluation"): # Modified to expect 2 values
    preds.append(model(X.to("cuda"), subject_idxs.to('cuda')).detach().cpu())

preds = torch.cat(preds, dim=0).numpy()
np.save("submission", preds)
print(f"Submission {preds.shape} saved.")

アンサンブル用/TTA

device='cuda'
def tta_augment(x, num_augs=4):

    B, C, T = x.shape
    xs = []

    #パターン0: オリジナル
    xs.append(x)

    for i in range(1, num_augs):
        x_aug = x.clone()

        #軽ランダム変形を1つだけ
        aug_type = torch.randint(0, 3, (1,)).item()

        if aug_type == 0:
            shift = torch.randint(-2, 3, (1,)).item()
            x_aug = torch.roll(x_aug, shifts=shift, dims=2)

        elif aug_type == 1:
            noise = torch.randn_like(x_aug) * 0.02
            x_aug = x_aug + noise

        elif aug_type == 2:
            t_len = torch.randint(5, 10, (1,)).item()
            t_start = torch.randint(0, T - t_len, (1,)).item()
            x_aug[:, :, t_start:t_start+t_len] = 0

        xs.append(x_aug)

    return xs  # list of (B, C, T)


batch_size = 128
test_set = ThingsEEGDataset("test")
test_loader = torch.utils.data.DataLoader(
    test_set, batch_size=batch_size, shuffle=False
)

def infer_tta_logits(model, testloader, device="cuda", numtta=4):
    model.eval()
    preds = []
    for X, subjectidxs in tqdm(testloader, desc="TTA inference"):
        X = X.to(device)
        subjectidxs = subjectidxs.to(device)

        xlist = tta_augment(X, num_augs=numtta)  #list of (B,17,100)
        logits_sum = 0.0
        with torch.no_grad():
            for xaug in xlist:
                logits_sum = logits_sum + model(xaug, subjectidxs)  # (B,5)

        logits_mean = logits_sum / len(xlist)  # (B,5)
        preds.append(logits_mean.detach().cpu())

    return torch.cat(preds, dim=0).numpy()  # (N,5)

'''
pretrain_model = MAEEG_Pretrain_Embedding(
    in_channels=17, time_steps=100, embed_dim=64, mask_ratio=0.5, num_subjects=11
).to(device)
'''
'''
pretrain_model = ConformerMAEEG_Pretrain(
    in_channels=17,
    time_steps=100,
    embed_dim=128, # Changed embed_dim to 128 to match saved model
    depth=4,       # Added depth=4 to match saved model
    mask_ratio=0.6, # Changed mask_ratio to 0.6 to match saved model
    num_subjects=11
    ).to(device)
'''
#model = EEGNetHybrid().to(device)

model = EEGConformer(
    num_classes=5,
    in_channels=17,
    time_steps=100,
    d_model=64,
    n_heads=4,
    n_layers=2,  # Conformerブロック数
    dropout=0.1,
    num_subjects=11
    ).to('cuda')

#model = MAEEG_Classifier_Embedding(pretrain_model, num_classes=5, num_subjects=11).to(device)

#model = ConformerMAEEG_Classifier(pretrain_model, num_classes=5, num_subjects=11).to(device)

model.load_state_dict(torch.load("model_best_eegconf.pt", map_location=device))
model.eval()
eegconf = infer_tta_logits(model, test_loader, device=device, numtta=4)
np.save("eegconf_logits_tta4.npy", eegconf)

# @title
#TTAなし
#例: MAEEG_SubjectEmbedding の test 予測を保存
import copy
device = "cuda"
batch_size = 128

test_set = ThingsEEGDataset("test")
test_loader = torch.utils.data.DataLoader(
    test_set, batch_size=batch_size, shuffle=False, num_workers=2, pin_memory=True
)


'''
pretrain_model = MAEEG_Pretrain_Embedding(
    in_channels=17, time_steps=100, embed_dim=64, mask_ratio=0.5, num_subjects=11
).to(device)
'''
pretrain_model = ConformerMAEEG_Pretrain(
    in_channels=17,
    time_steps=100,
    embed_dim=128, #Changed embed_dim to 128 to match saved model
    depth=4,
    mask_ratio=0.6,
    num_subjects=11
    ).to(device)

#model = EEGNetHybrid().to(device)
'''
model = EEGConformer(
    num_classes=5,
    in_channels=17,
    time_steps=100,
    d_model=64,
    n_heads=4,
    n_layers=2,  # Conformerブロック数
    dropout=0.1,
    num_subjects=11
    ).to('cuda')
    '''
#model = MAEEG_Classifier_Embedding(pretrain_model, num_classes=5, num_subjects=11).to(device)

model = ConformerMAEEG_Classifier(pretrain_model, num_classes=5, num_subjects=11).to(device)

model.load_state_dict(torch.load("mae_classifier_best.pt", map_location=device))
model.eval()

all_logits = []
with torch.no_grad():
    for X, subject_idxs in tqdm(test_loader, desc="MAEEG_SubEmb Test"):
        X = X.to(device)
        subject_idxs = subject_idxs.to(device)
        logits = model(X, subject_idxs)   # (B,5), NOT softmax
        all_logits.append(logits.cpu())

all_logits = torch.cat(all_logits, dim=0).numpy()  # (59400,5)
np.save("Confmaeeg_subemb_test_logits.npy", all_logits)

"""## 提出方法

以下の3点をzip化し，Omnicampusの「最終課題 (EEG)」から提出してください．

- `submission.npy`
- `model_last.pt`や`model_best.pt`など，テストに使用した重み（拡張子は`.pt`のみ）
- 本Colab Notebook
"""

# @title
#ロジットを読み込み
logits_mae   = np.load("maeeg_logits_tta4.npy")      # (N,5)
logits_conf  = np.load("eegconf_logits_tta4.npy")       # (N,5)
logits_eeg   = np.load("eeghyb_logits_tta4.npy")          # (N,5)
logits_confmae = np.load('maeconf_logits_tta4.npy')

val_confmae, val_mae, val_conf, val_eeg = 0.54, 0.52, 0.51, 0.49
wsum = val_confmae + val_mae + val_conf + val_eeg
w_confmae, w_mae, w_conf, w_eeg = val_confmae/wsum, val_mae/wsum, val_conf/wsum, val_eeg/wsum

#重み付きロジット平均
logits_ens = w_confmae*logits_confmae + w_mae*logits_mae + w_conf*logits_conf + w_eeg*logits_eeg  # (N,5)

# 提出用確率
#probs = torch.softmax(torch.from_numpy(logits_ens), dim=-1).numpy()
#np.save("submission_ensemble_weightedAVG.npy", probs)

# 最終確率 or そのまま argmax
probs = torch.softmax(torch.from_numpy(logits_ens), dim=-1).numpy()
np.save("submission.npy", probs)

from zipfile import ZipFile

model_path = "mae_classifier_best.pt"
notebook_path = '/content/drive/MyDrive/Colab Notebooks/DLBasics2025_competition_EEG_v8_MAEEGConformer.ipynb'
#'/content/drive/MyDrive/Colab_Notebooks/DLbasic/FinalAssignment/DLBasics2025_competition_EEG_v8_MAEEGConformer.ipynb'

# '/workspace/EEG/DLBasics2025_competition_EEG_v8_MAEEGConformer.ipynb'
#"/content/drive/MyDrive/Colab_Notebooks/DLbasic/FinalAssignment/DLBasics2025_competition_EEG_v7.ipynb"

with ZipFile("submission_MEAConfTTAensemble3.zip", "w") as zf:
    zf.write("submission.npy")
    zf.write(model_path)
    zf.write(notebook_path)

